### ISSUE TITLE
在login的时候发生错误

### ISSUE THREAD

**Issue by xlzd** [taizilongxu/weibo_robot#1]
在login的时候报错,错误为:
weibo.APIError: APIError: 21325: invalid_grant, request: /oauth2/access_token
报错语句为:
r = client.request_access_token(code)
请问应该怎么解决呢?

**Comment by taizilongxu** [comment]
恩, 今天试了下,发现code的方法已经不管用了, 改了一下,现在应当能用了

**Comment by xlzd** [comment]
from weibo import Client

这个还是不行啊,  cannot import name Client

**Comment by taizilongxu** [comment]
忘了说 需要 `pip install weibo` 一下

**Comment by xlzd** [comment]
weibo是安装了的,有APIClient, 没有 Client呀~~~

**Comment by taizilongxu** [comment]
换成weibo包了, 不是snowweibopy这个包, 是不是这个问题?

**Comment by xlzd** [comment]
http://github.liaoxuefeng.com/sinaweibopy/
请问是这个吗?

**Comment by taizilongxu** [comment]
是这个 https://github.com/lxyu/weibo

**Comment by xlzd** [comment]
谢谢~~~

**Comment by taizilongxu** [comment]
OK,  我readme里可能没写清除, 一会我加一下

**Comment by jekoy** [comment]
Login success
Listening...
Thu May 25 20:15:42 2017 shutdown -p
Thu May 25 20:15:52 2017 shutdown -p
Thu May 25 20:15:52 2017 shutdown -p.....
错误如上，是哪里出错了呢？
