### ISSUE TITLE
pip install weibo 报错

### ISSUE THREAD

**Issue by tianwei1992** [taizilongxu/weibo_robot#3]
C:\Users\Administrator>pip install weibo
Collecting weibo
  Using cached weibo-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-bsc3gh9w\weibo\setup.
py", line 15, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 241: ille
gal multibyte sequence

**Comment by lily19970201** [comment]
我的也是。找到解决方法了吗

**Comment by tianwei1992** [comment]
没有。。换itchat了
